channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.8.1
  - catboost==1.2.2
  - cloudpickle==2.2.1
  - ipython==8.18.0
  - numpy==1.25.2
  - packaging==23.2
  - pandas==2.0.3
  - psutil==5.9.6
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
