artifact_uri: file:///home/dwna/projects/domain_class/models/216902294232963657/fb8de01e139040cd87359f44cca949ac/artifacts
end_time: null
entry_point_name: ''
experiment_id: '216902294232963657'
lifecycle_stage: active
run_id: fb8de01e139040cd87359f44cca949ac
run_name: adventurous-crab-91
run_uuid: fb8de01e139040cd87359f44cca949ac
source_name: ''
source_type: 4
source_version: ''
start_time: 1701328398924
status: 1
tags: []
user_id: dwna
