channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==2.2.1
  - dask==2023.11.0
  - graphviz==0.20.1
  - importlib-metadata==6.8.0
  - jinja2==3.1.2
  - lightgbm==4.1.0
  - matplotlib==3.7.3
  - numpy==1.25.2
  - packaging==23.2
  - pandas==2.0.3
  - psutil==5.9.6
  - pyarrow==14.0.1
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
