channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=23.3.1
- pip:
  - mlflow==2.8.1
  - catboost==1.2.2
  - cloudpickle==2.2.1
  - ipywidgets==8.1.1
  - numpy==1.24.4
  - packaging==23.2
  - pandas==2.0.3
  - psutil==5.9.6
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
